# Generated by Django 4.1.5 on 2023-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterField(
            model_name='labtest',
            name='medical_images',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images'),
        ),
    ]
