# Generated by Django 4.1.5 on 2023-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0002_alter_diagnosis_options_alter_labtest_medical_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billed_to',
            field=models.CharField(choices=[('NHIF', 'NHIF'), ('INSURANCE COMPANY', 'INSURANCE COMPANY'), ('PATIENT', 'PATIENT'), ('PATIENT and NHIF', 'PATIENT and NHIF')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine_type',
            field=models.CharField(choices=[('Pain relievers', 'Pain relievers'), ('Tranquilizers', 'Tranquilizers'), ('Stimulants', 'Stimulants'), ('Sedatives', 'Sedatives')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('Acute (not to be repeated)', 'Acute (not to be repeated)'), ('Repeat (long term medication)', 'Repeat (long term medication)'), ('Repeat Dispensing (specific amount of ussues)', 'Repeat Dispensing (specific amount of ussues)')], max_length=100),
        ),
    ]
