# Generated by Django 4.1.5 on 2023-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0003_alter_bill_billed_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalvisit',
            name='date_recorded',
        ),
    ]
