# Generated by Django 4.1.5 on 2023-01-29 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0004_remove_hospitalvisit_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvisit',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
