# Generated by Django 4.1.5 on 2023-02-08 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0006_remove_labtest_medical_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='pre_existing_conditions',
        ),
        migrations.DeleteModel(
            name='PreexistingCondition',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pre_existing_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
            preserve_default=False,
        ),
    ]
