# Generated by Django 4.1.5 on 2023-02-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0008_remove_labtest_finding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='pre_existing_conditions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
