# Generated by Django 4.1.5 on 2023-02-21 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_records', '0013_rename_bill_status_hospitalvisit_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='edited_by',
            field=models.ManyToManyField(blank=True, related_name='h_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
