# Generated by Django 4.1.5 on 2023-02-22 00:04

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0016_alter_hospitalvisit_billed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='bill',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='KES', max_digits=14),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='billed_to',
            field=models.CharField(choices=[('NHIF', 'NHIF'), ('INSURANCE COMPANY', 'INSURANCE COMPANY'), ('PATIENT', 'PATIENT'), ('PATIENT and NHIF', 'PATIENT and NHIF')], max_length=100),
        ),
    ]
