# Generated by Django 4.1.5 on 2023-02-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_records', '0019_alter_hospitalvisit_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
