# Generated by Django 4.1.5 on 2023-03-06 16:31

from django.db import migrations, models
import p_records.models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0023_hospitalvisit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='name',
            field=models.CharField(default=p_records.models.generate_default_name, max_length=100),
        ),
    ]
