# Generated by Django 4.1.5 on 2023-02-22 20:03

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id_no',
            field=models.PositiveIntegerField(unique=True, validators=[authenticator.models.validate_digits]),
        ),
    ]
