# Generated by Django 4.1.5 on 2023-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001FFCFA758A0>', max_length=200),
        ),
    ]
