# Generated by Django 4.1.5 on 2023-01-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0005_hospitalvisit_date_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='medical_images',
        ),
    ]
