# Generated by Django 4.1.5 on 2023-02-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0007_remove_healthrecord_pre_existing_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_type',
        ),
    ]
