# Generated by Django 4.1.5 on 2023-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0010_alter_healthrecord_pre_existing_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalvisit',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='hospitalvisit',
            name='prescriptions',
        ),
        migrations.RemoveField(
            model_name='hospitalvisit',
            name='tests',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='prescriptions',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='tests',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
