# Generated by Django 4.1.5 on 2023-02-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0012_hospitalvisit_bill_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='bill_status',
            new_name='paid',
        ),
    ]
