# Generated by Django 4.1.5 on 2023-02-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0015_alter_hospitalvisit_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='billed_to',
            field=models.CharField(blank=True, choices=[('NHIF', 'NHIF'), ('INSURANCE COMPANY', 'INSURANCE COMPANY'), ('PATIENT', 'PATIENT'), ('PATIENT and NHIF', 'PATIENT and NHIF')], max_length=100),
        ),
    ]
