# Generated by Django 4.1.5 on 2023-02-22 19:22

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0017_alter_hospitalvisit_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='pre_existing_conditions',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, max_length=200)),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='diagnosis',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, max_length=200)),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='prescriptions',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, max_length=200)),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='tests',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, max_length=200)),
        ),
    ]
