# Generated by Django 4.1.5 on 2023-02-22 19:47

from django.conf import settings
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_records', '0018_alter_healthrecord_pre_existing_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='diagnosis',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='edited_by',
            field=models.ManyToManyField(related_name='h_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='prescriptions',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='tests',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=200)),
        ),
    ]
