# Generated by Django 4.1.5 on 2023-03-06 16:28

from django.db import migrations, models
import p_records.models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records', '0022_alter_healthrecord_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvisit',
            name='name',
            field=models.CharField(default=p_records.models.generate_default_name, max_length=10),
        ),
    ]
